package com.webengage.personalization.utils

class Properties {

    companion object View {
        const val Height = "ht"
        const val Weight = "weight"
        const val Width = "wd"
        const val Background = "bg"
        const val Alpha = "alpha"
        const val LayoutPosition = "pos"
        const val CENTER = "center"
        const val CENTER_HORIZONTAL = "center_horizontal"
        const val CENTER_VERTICAL = "center_vertical"
        const val LEFT = "left"
        const val RIGHT = "right"
        const val TOP = "top"
        const val BOTTOM = "bottom"
        const val START = "start"
        const val END = "end"
        const val Margin = "margin"
        const val MarginBottom = "mb"
        const val MarginLeft = "ml"
        const val MarginRight = "mr"
        const val MarginTop = "mt"
        const val MarginStart = "marginStart"
        const val MarginEnd = "marginEnd"
        const val Padding = "padding"
        const val PaddingBottom = "paddingBottom"
        const val PaddingEnd = "paddingEnd"
        const val PaddingLeft = "paddingLeft"
        const val PaddingRight = "paddingRight"
        const val PaddingStart = "paddingStart"
        const val PaddingTop = "paddingTop"
        const val CornerRadius = "cr"
        const val BorderColor = "bc"
        const val BorderWidth = "bw"
        const val Shadow = "shdw"
        const val FONT_NAME = "af"
        const val ACTION_URL = "aUrl"
        const val SRC = "src"
        const val SCALE_TYPE = "st"
    }

    object TextView {
        const val Gravity = "gravity"
        const val Text = "text"
        const val HTML = "html"
        const val TextSize = "textSize"
        const val TextColor = "tc"
        const val TextAlignment = "textAlignment"
        const val TextColorHint = "textColorHint"
        const val TextColorLink = "textColorLink"
        const val TextColorHighLight = "textColorHighlight"
        const val DrawableLeft = "drawableLeft"
        const val DrawableRight = "drawableRight"
        const val DrawableTop = "drawableTop"
        const val DrawableBottom = "drawableBottom"
        const val DrawablePadding = "drawablePadding"
        const val MaxLines = "mxl"
        const val Ellipsize = "ellipsize"
        const val PaintFlags = "paintFlags"
        const val Prefix = "prefix"
        const val Suffix = "suffix"
        const val TextStyle = "textStyle"
        const val SingleLine = "singleLine"
        const val TextAllCaps = "textAllCaps"
        const val Hint = "hint"
        const val IS_ITALICS = "isItal"
        const val IS_BOLD = "isBold"
        const val IS_UNDER_LINE = "isUnderLine"
        const val LineBreakMode = "lbm"
    }

    object Keys {
        const val CallToAction = "cta"
    }
}