
struct WEConstants{
    static let PERSONALIZATION_SDK = "react_personalization_sdk";
    static let CHANNEL_INLINE_VIEW = "channel_inline_view"
    static let PAYLOAD_IOS_PROPERTY_ID = "iosPropertyId"
    static let PAYLOAD_SCREEN_NAME = "screenName"
    static let PAYLOAD_ID = "id"
    static let PAYLOAD_DATA = "data"
    static let PAYLOAD = "payloadData"
    static let PAYLOAD_CAMPAIGN_ID = "campaignID"
    static let PAYLOAD_TARGET_VIEW_ID = "targetViewId"
    static let PAYLOAD_ERROR = "error"
    static let PAYLOAD_VIEW_WIDTH = "viewWidth"
    static let PAYLOAD_VIEW_HEIGHT = "viewHeight"
    static let PAYLOAD_ACTION_ID = "actionId"
    static let PAYLOAD_DEEPLINK = "deeplink"
    static let SCREEN_NAVIGATED = "screenNavigated"
    static let TAG = "WEH: "
    static let EXCEPTION = "exception"
    static let PAYLOAD_WEGDATA = "wegData"
    static let METHOD_NAME_ON_DATA_RECEIVED = "onDataReceived"
    static let METHOD_NAME_ON_PLACEHOLDER_EXCEPTION = "onPlaceholderException"
    static let METHOD_NAME_ON_RENDERED = "onRendered"
    static let METHOD_NAME_WEG_DATA_LISTENER = "wegInlineDataListener"
    static let METHOD_NAME_REGISTER = "register"
    static let METHOD_NAME_DEREGISTER = "deregister"
    static let METHOD_NAME_INIT = "init"
    static let METHOD_NAME_ON_CAMPAIGN_CLICKED = "onCampaignClicked"
    static let METHOD_NAME_ON_CAMPAIGN_EXCEPTION = "onCampaignException"
    static let METHOD_NAME_ON_CAMPAIGN_PREPARED = "onCampaignPrepared"
    static let METHOD_NAME_ON_CAMPAIGN_SHOWN = "onCampaignShown"
}
